import { usePageTitle } from '../hooks/usePageTitle';

export function HomePage() {
  usePageTitle();

  return (
    <div className="page-content">
      <div className="card mb-2">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis magna purus. Nulla sit amet leo dignissim, scelerisque quam quis, convallis lorem. Integer lacinia augue id lorem finibus hendrerit. Nulla orci risus, auctor eu arcu sit amet, accumsan fringilla lectus. Duis malesuada mollis massa et cursus. Quisque ac mollis metus. Curabitur id libero dapibus velit cursus imperdiet. Proin ut ipsum quis elit mollis auctor. Mauris sodales lacus lacinia mi tristique, ut pretium purus mattis.<br/><br/>
          Suspendisse potenti. Maecenas aliquam quam ac nibh consectetur, ut facilisis erat blandit. Maecenas in mattis purus, vitae interdum mauris. Mauris sagittis nulla enim, in sollicitudin lectus maximus at. Maecenas faucibus dolor eget consequat pulvinar. Aliquam non convallis velit, suscipit gravida arcu. Phasellus non augue arcu. Vestibulum laoreet risus pellentesque posuere vehicula. Aliquam eget turpis a ligula finibus tempor. Quisque pharetra commodo orci quis maximus. In scelerisque metus at lectus pharetra tristique.<br/><br/>
          Quisque vulputat leo sit amet sodales auctor. Etiam feugiat nulla vitae enim facilisis, sit amet faucibus nisi rutrum. Mauris pharetra leo eu vestibulum dictum. Nunc eu ullamcorper ligula, varius laoreet nulla. Nunc eget ipsum sit amet lectus rhoncus hendrerit. Nunc consequat tempus libero, id pulvinar neque dictum ac. Sed a vehicula felis, et suscipit quam. Maecenas placerat congue rhoncus. Etiam mattis mi quis sollicitudin dignissim. Quisque vulputate, eros sed aliquam pulvinar, augue felis cursus urna, sit amet sagittis nisl eros eu erat. Duis nunc lectus, lacinia eget eleifend sed, consequat et neque. Morbi eleifend tellus nec placerat accumsan. Donec dictum, sapien quis semper ultrices, risus nibh dignissim mi, id congue elit neque vel libero.<br/><br/>
          Fusce aliquam justo vel aliquam lacinia. Suspendisse ut neque tellus. Integer dapibus nec ex vel luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed ipsum erat, sodales at ullamcorper non, porttitor eget eros. Nullam sagittis dignissim suscipit. Nulla facilisi.<br/><br/>
          Praesent vitae ullamcorper turpis. Maecenas elementum a massa pharetra auctor. Suspendisse malesuada neque in bibendum pellentesque. Fusce pulvinar urna sit amet ipsum rhoncus, nec efficitur lacus feugiat. Proin ullamcorper vehicula luctus. Maecenas vel ultrices magna, a rhoncus urna. Pellentesque convallis justo eu turpis sodales, et cursus lorem convallis. Vivamus a leo lorem. Duis non gravida diam. Donec commodo porttitor purus a tincidunt. Morbi sollicitudin velit augue, a faucibus eros ullamcorper non. Phasellus vehicula id tortor nec laoreet. Sed sed tortor leo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.<br/><br/>
          Etiam pharetra, diam egestas pharetra sollicitudin, mauris erat dictum velit, et imperdiet elit enim sit amet tortor. Suspendisse consequat dolor id elementum finibus. Donec sapien quam, pharetra sed facilisis at, sagittis eu metus. Vestibulum vel varius enim. Nulla volutpat consectetur velit, et elementum purus euismod id. Proin at aliquam erat. Vestibulum lacinia nec eros et pellentesque. Morbi elementum nibh ut eleifend finibus. Pellentesque urna mauris, porta tincidunt tortor ac, vestibulum elementum quam. Praesent lobortis eros ligula, sed faucibus turpis convallis vitae. In volutpat ex ac purus egestas, ut placerat sem facilisis. Maecenas aliquam purus ac libero finibus imperdiet eu sollicitudin lacus. Integer sodales laoreet libero vel iaculis. Mauris scelerisque nibh diam, hendrerit accumsan augue molestie sed. Aenean lobortis faucibus metus, aliquet dignissim est fermentum eu.<br/><br/>
          Cras maximus, augue eget scelerisque venenatis, neque tellus rutrum risus, eget tincidunt elit augue sit amet risus. Nullam cursus bibendum neque a interdum. Morbi egestas, velit et gravida pharetra, arcu nisi iaculis enim, sit amet faucibus urna sapien sed ipsum. Integer aliquet et ante in volutpat. Fusce condimentum turpis eget orci tristique tempus. Suspendisse tortor mi, malesuada sed sem vitae, malesuada vestibulum massa. Fusce eleifend ut sem et ultrices. Aliquam urna quam, posuere fermentum dignissim ac, dapibus in lorem. Vestibulum tristique velit in ex molestie scelerisque. Mauris laoreet pellentesque lobortis. Nulla tempor, urna in feugiat mattis, massa mi aliquet dui, ac finibus leo dui sed sem. Phasellus scelerisque ultricies dolor sed fringilla. Mauris finibus venenatis dictum.<br/><br/>
          Vivamus ultrices porta nisl, eu euismod tortor aliquam sit amet. Nam gravida non mauris sed tempor. Nam pharetra rutrum odio eu vestibulum. Pellentesque placerat tempor turpis, eget tempor augue mollis eu. Pellentesque vitae dui sit amet nisi imperdiet dapibus. Phasellus rhoncus felis et ipsum dictum suscipit. Cras tincidunt, lacus sit amet volutpat accumsan, metus mi bibendum velit, in condimentum mauris diam sit amet justo. Vivamus non neque a erat porttitor suscipit. In vulputate, turpis accumsan finibus efficitur, lacus mauris aliquet diam, ut viverra sem mauris sed lectus. Integer gravida rhoncus ligula. Nullam eu magna sapien. Cras elementum ipsum nec neque facilisis, nec porta mauris aliquam. Sed risus est, porttitor eget sodales mollis, lobortis id ipsum. Donec eget sapien sapien. Suspendisse laoreet augue quam, vel auctor dolor posuere at.<br/><br/>
          Sed sed neque nibh. Phasellus cursus, tellus ut condimentum tempus, ipsum orci venenatis nulla, eget mollis turpis mauris at lectus. Quisque vitae dui porttitor, porta eros a, pulvinar turpis. Nullam et condimentum libero. Pellentesque pellentesque nisl luctus gravida rutrum. Aliquam tristique consequat odio, in iaculis elit sagittis quis. Morbi posuere justo quam, vel varius felis finibus vitae. Vivamus venenatis nunc turpis, a rutrum sem posuere molestie. Vestibulum cursus, ipsum ut euismod fermentum, urna ante bibendum neque, porta luctus nulla sapien in ligula. Ut at augue a enim iaculis molestie eget et justo.<br/><br/>
          In et viverra augue. Vivamus euismod arcu in ornare accumsan. Vivamus facilisis vehicula neque in bibendum. Duis dapibus sapien auctor urna aliquam, eget gravida eros semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam blandit urna tincidunt nunc lacinia sollicitudin. Aenean dignissim hendrerit congue. Nam maximus, quam id tristique consequat, mi diam accumsan turpis, sit amet cursus tortor nisl vel lacus. Ut id nulla mollis, iaculis nulla eget, dictum dui. Sed ex nulla, dignissim ac hendrerit non, tincidunt eu arcu.
        </p>
      </div>
    </div>
  );
}
